--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Terpz710/EnderKits
build-by-default: true
branches:
- main
projects:
  EnderKits:
    path: ""
    icon: icon.PNG
    lint:
      phpstan: false
...
