name: EnderKits
author: Terpz710
main: Terpz710\EnderKits\Main
version: 1.0.0-alpha
api: [5.0.0]
description: EnderKits plugin for Pocketmine-MP.
depend: [RankSystem]
softdepend: [PiggyCustomEnchants, BankNotesPlus]

permissions:
  enderkits.command.kit:
    description: "Enderkits Perm"
    default: true
  enderkits.command.kits:
    description: "Enderkits Perm"
    default: true
